# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cab993e712d756ee918d61c76128729de796c85de22349632b2e67d8240f94e6768f74b9402c3eae2e0f6fdfea7f6e1444d9339163ab544191bbe026aa199259

test:
  secret_key_base: e11daca97fbe722805e9c321d8d85b338a41dc2fa0025f7a5fa8729e2a700dccb02ef593f077a1b474365dbc7393b095a28953801e5f6a5b20109b8d6be4c839

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
